name: showcaseview
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 5.0.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/showcaseview/issues
repository: https://github.com/SimformSolutionsPvtLtd/showcaseview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
